export const BRAND = {
  name: 'ULTHOR SUPLEMENTOS',
  tagline: 'Forje seu corpo com suplementos premium',
  email: 'ulthorsuplementos@gmail.com',
  phone: '(11) 92473-0574',
  phoneRaw: '5511924730574',
  instagram: '@ulthorsuplementos',
  instagramUrl: 'https://instagram.com/ulthorsuplementos',
  whatsappUrl: 'https://wa.me/5511924730574',
  adminEmail: 'ulthorsuplementos@gmail.com',
} as const

export const CATEGORIES = [
  { nome: 'Whey Protein', slug: 'whey-protein', icon: 'Dumbbell' },
  { nome: 'Creatina', slug: 'creatina', icon: 'Zap' },
  { nome: 'Pré-Treino', slug: 'pre-treino', icon: 'Flame' },
  { nome: 'Hipercalórico', slug: 'hipercalorico', icon: 'TrendingUp' },
  { nome: 'Vitaminas', slug: 'vitaminas', icon: 'Heart' },
  { nome: 'Emagrecedores', slug: 'emagrecedores', icon: 'Target' },
  { nome: 'Ganho de Massa', slug: 'ganho-de-massa', icon: 'Award' },
  { nome: 'Acessórios', slug: 'acessorios', icon: 'ShoppingBag' },
] as const

export const DEMO_PRODUCTS = [
  {
    id: '1',
    nome: 'Whey Protein Gold 900g',
    slug: 'whey-protein-gold-900g',
    descricao: 'Whey protein concentrado de alta qualidade com 24g de proteína por dose.',
    beneficios: ['Aumento de massa muscular', 'Recuperação pós-treino', 'Alto teor proteico'],
    modo_uso: 'Misture 1 scoop (30g) em 200ml de água ou leite. Consumir após o treino.',
    preco: 149.9,
    estoque: 50,
    categoria: 'Whey Protein',
    imagens: ['https://images.unsplash.com/photo-1579722821275-0aa034a1e994?w=600&h=600&fit=crop'],
    destaque: true,
    ativo: true,
  },
  {
    id: '2',
    nome: 'Creatina Monohidratada 300g',
    slug: 'creatina-monohidratada-300g',
    descricao: 'Creatina pura monohidratada para aumento de força e performance.',
    beneficios: ['Aumento de força', 'Melhora de performance', 'Recuperação muscular'],
    modo_uso: 'Consumir 1 scoop (5g) diluído em água, preferencialmente pós-treino.',
    preco: 89.9,
    estoque: 80,
    categoria: 'Creatina',
    imagens: ['https://images.unsplash.com/photo-1579722821275-0aa034a1e994?w=600'],
    destaque: true,
    ativo: true,
  },
  {
    id: '3',
    nome: 'Pré-Treino Thunder 300g',
    slug: 'pre-treino-thunder-300g',
    descricao: 'Pré-treino explosivo com cafeína, beta-alanina e arginina.',
    beneficios: ['Energia e foco', 'Pump muscular', 'Resistência'],
    modo_uso: 'Consumir 1 scoop (10g) 30 minutos antes do treino.',
    preco: 119.9,
    estoque: 35,
    categoria: 'Pré-Treino',
    imagens: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600'],
    destaque: true,
    ativo: true,
  },
  {
    id: '4',
    nome: 'Hipercalórico Mass 3kg',
    slug: 'hipercalorico-mass-3kg',
    descricao: 'Hipercalórico completo para ganho de peso e massa muscular.',
    beneficios: ['Ganho de peso', 'Calorias extras', 'Carboidratos complexos'],
    modo_uso: 'Misture 2 scoops (150g) em 400ml de leite integral. Consumir 2x ao dia.',
    preco: 179.9,
    estoque: 25,
    categoria: 'Hipercalórico',
    imagens: ['https://images.unsplash.com/photo-1571019614242-c5c5dee9f50e?w=600'],
    destaque: false,
    ativo: true,
  },
  {
    id: '5',
    nome: 'Multivitamínico Complete',
    slug: 'multivitaminico-complete',
    descricao: 'Complexo vitamínico completo com 25 vitaminas e minerais.',
    beneficios: ['Saúde geral', 'Imunidade', 'Energia diária'],
    modo_uso: 'Consumir 1 cápsula ao dia com uma refeição.',
    preco: 69.9,
    estoque: 100,
    categoria: 'Vitaminas',
    imagens: ['https://images.unsplash.com/photo-1550572017-edd951aa8fdc?w=600'],
    destaque: false,
    ativo: true,
  },
  {
    id: '6',
    nome: 'Termogênico Burn Max',
    slug: 'termogenico-burn-max',
    descricao: 'Termogênico avançado para acelerar o metabolismo.',
    beneficios: ['Queima de gordura', 'Acelera metabolismo', 'Controle de apetite'],
    modo_uso: 'Consumir 2 cápsulas pela manhã em jejum.',
    preco: 99.9,
    estoque: 40,
    categoria: 'Emagrecedores',
    imagens: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600'],
    destaque: false,
    ativo: true,
  },
  {
    id: '7',
    nome: 'BCAA 2:1:1 300g',
    slug: 'bcaa-211-300g',
    descricao: 'Aminoácidos de cadeia ramificada para recuperação muscular.',
    beneficios: ['Anti-catabolismo', 'Recuperação', 'Resistência'],
    modo_uso: 'Consumir 1 scoop (10g) durante ou após o treino.',
    preco: 79.9,
    estoque: 60,
    categoria: 'Ganho de Massa',
    imagens: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600'],
    destaque: true,
    ativo: true,
  },
  {
    id: '8',
    nome: 'Shaker Premium 700ml',
    slug: 'shaker-premium-700ml',
    descricao: 'Shaker premium com compartimento para suplementos.',
    beneficios: ['Praticidade', 'Sem vazamentos', 'BPA Free'],
    modo_uso: 'Utilize para misturar seus suplementos.',
    preco: 39.9,
    estoque: 120,
    categoria: 'Acessórios',
    imagens: ['https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600'],
    destaque: false,
    ativo: true,
  },
] as const

export const DEMO_BANNERS = [
  {
    id: '1',
    titulo: 'FORJA SEU CORPO',
    subtitulo: 'Suplementos premium para resultados épicos',
    imagem: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1920',
    link: '/produtos',
    ativo: true,
    ordem: 1,
  },
  {
    id: '2',
    titulo: 'WHEY PROTEIN GOLD',
    subtitulo: 'Até 30% OFF na linha premium',
    imagem: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989f?w=1920',
    link: '/categorias/whey-protein',
    ativo: true,
    ordem: 2,
  },
  {
    id: '3',
    titulo: 'PRÉ-TREINO THUNDER',
    subtitulo: 'Energia de um deus',
    imagem: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1920',
    link: '/categorias/pre-treino',
    ativo: true,
    ordem: 3,
  },
] as const
